jobs:  
  include:
    - stage: backend
      language: python
      python:
        - "3.6"
      script:
        - pytest --ignore=integration_tests

    - stage: frontend
      language: node_js
      node_js:
        - "lts/*"
      before_install:
        - cd ./ui
      install:
        - npm install
      script:
        - npm test
